name: Bug report
description: File a bug report
title: "[BUG] "
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug
    validations: { required: true }
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
  - type: input
    id: url
    attributes:
      label: Affected URL (if any)
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options: [P0, P1, P2, P3]
    validations: { required: true }
