name: Feature request
description: Suggest a new feature
title: "[FEAT] "
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
  - type: textarea
    id: risks
    attributes:
      label: Risks / roll-out plan
