name: Task
description: Track a unit of work
title: "[TASK] "
labels: [task]
body:
  - type: textarea
    id: scope
    attributes:
      label: Scope
  - type: textarea
    id: dod
    attributes:
      label: Definition of Done
  - type: textarea
    id: deps
    attributes:
      label: Dependencies
  - type: textarea
    id: tests
    attributes:
      label: Required tests
